### ISSUE TITLE
Grand Prize Bag wrong item

### ISSUE THREAD

**Issue by ming0328ming** [CaiganMythFang/TheFerretBusinessIssues#54] opened 2017-12-20 21:30 UTC
Grand Prize Bag gives you hearts (6809) instead of blindbags (6810)

**Comment by CaiganMythFang** [comment] 2018-01-18 14:36
Whoops, missed this one being posted earlier, a newer one mentioned this issue as well.

**Comment by CaiganMythFang** [comment] 2018-01-18 14:36
Duplicate of #59

**Comment by CaiganMythFang** [comment] 2018-02-24 19:56
Fixed in 0.2.6

**Closed as completed by CaiganMythFang** 2018-02-24 19:56 UTC
Labels: FIXED IN PREV UPDATE
